### ISSUE TITLE
Create authentication method

### ISSUE THREAD

**Issue by pedrochaves** [ezdeliveryco/snorlax#43]
The original previously written did not work with the current versions Guzzle, so we need a way to authenticate every request automatically.

The old way was removed in #42, in case we need a reference.

**Comment by jmauerhan** [comment]
I've actually done this in another project I worked on, there's a way to add request options to an existing request. I'd be happy to work on this one.

**Comment by pedrommone** [comment]
Hello @jmauerhan, thank you for sharing you knowledge with us! We're waiting your PR.

**Comment by jmauerhan** [comment]
I'm not super familiar with your tool, so forgive me if this question seems obvious - how is RestClient used to actually make requests? Do users call `getOriginalClient` and then make requests based on the `\GuzzleHttp\ClientInterface`?

If so, I'd suggest changing this approach to actually use your own client class with a request method. I can't see anywhere in the codebase that requests using the `\GuzzleHttp\ClientInterface` are ever actually made. 

It's easy in the case of the Default client being used because you've specified an implementation of `\GuzzleHttp\ClientInterface` which has more methods - I think you may be too tightly coupling your project's classes with Guzzle's classes. I'd use more of an Interface/Adapter approach to make these sorts of changes more seamless. 

Anyway, if someone can explain where the actual request happens, I can probably help a lot more. As of now I'm slightly confused about how Guzzle is ultimately used here. :) 

Thanks and I'm happy to help any way I can!

**Comment by pedrochaves** [comment]
Hi @jmauerhan! Thanks for the help you've been giving us 😃 

The actual requests happen on `Snorlax\Resource::__call()` and they use the `GuzzleHttp\ClientInterface::request` method.

Basically, when constructing a `Snorlax\RestClient`, the user informs the `resources` that REST client has. These resources must be classes that inherit from `Snorlax\Resource` and defines actions, as seen in the [main example](https://github.com/ezdeliveryco/snorlax#basic-usage) on the README file.

And you're right about being too tightly coupling on Guzzle's interface. I like the idea of having a Snorlax kind of interface for these clients to make it easier to create all sorts of drivers, adapters, etc.

If you have any more doubts just let us know. Thanks!

**Comment by jmauerhan** [comment]
Okay great! I think I can move forward with adding the auth method back in and I'll have to add some logic to `Resource::__call`. 

As a separate PR, I'll work on an Interface to decouple your client from Guzzle. This would allow anyone to make an adapter for any HTTP client such as Guzzle, or use an older Guzzle version with a custom adapter, or whatever other library (I know there are others I just always use Guzzle myself so the names escape me! :-P ) Right now you almost have this (From reading your "Using a custom client" in the Readme) but it's still tied to the Guzzle library, so it's a small change that would add a lot of flexibility.

**Comment by jmauerhan** [comment]
Hey, sorry it's been a week, I was really busy last week with interviews.

I got this done, I had to change a few major things, but my hope is that it makes sense to you guys to do it this way. 

I will open a PR shortly with the changes. Basically, `Resource` now accepts a `RestClient` instead of the Guzzle `ClientInterface`. Resource doesn't care if you're using Guzzle or any other client, it will only communicate with the methods on `RestClient`. For easy BC, the `request` method on `RestClient` has the same signature as the Guzzle request method. This method is where we add in the extra auth parameters if they were already set.
